<?php

/**
 * @file
 * Provides functionality needed for Carbray Fullcalendar integration.
 */

use Drupal\Core\Render\Markup;
use Drupal\user\Entity\User;

function get_calendar_actuaciones($worker_uid = 0, $department_tid = 0) {
  $sql = "SELECT field_actuacion_tiempo_en_seg_value as minutes, nid, field_actuacion_expediente_target_id as expediente_nid, created, title, field_departamento_target_id as departamento_tid, uid as author, field_nombre_value as nombre, field_apellido_value as apellido, name as departamento
FROM node_field_data nfd
INNER JOIN node__field_actuacion_expediente ac on nfd.nid = ac.entity_id
INNER JOIN node__field_actuacion_tiempo_en_seg t on nfd.nid = t.entity_id
INNER JOIN user__field_departamento d on nfd.uid = d.entity_id
INNER JOIN user__field_nombre n on nfd.uid = n.entity_id
INNER JOIN user__field_apellido a on nfd.uid = a.entity_id
INNER JOIN user__roles ur on ur.entity_id = nfd.uid
INNER JOIN taxonomy_term_field_data term on term.tid = d.field_departamento_target_id
WHERE type = 'actuacion'";
  if ($worker_uid) {
    $sql .= " AND uid = $worker_uid";
  }
  if ($department_tid) {
    $tids = implode(',', $department_tid);
    $sql .= " AND field_departamento_target_id IN ($tids) AND roles_target_id != 'carbray_administrator'";
  }
  $actuaciones = \Drupal::database()->query($sql)->fetchAll();
  return $actuaciones;
}

function get_calendar_citas($worker_uid = 0, $department_tid = 0) {
  $sql = "SELECT field_cita_hora_value as hora, nid, field_cita_invitado_target_id as invitado_uid, created, title, field_departamento_target_id as departamento_tid, uid as author, field_nombre_value as nombre, field_apellido_value as apellido, name as departamento
FROM node_field_data nfd
LEFT JOIN node__field_cita_hora ch on nfd.nid = ch.entity_id
LEFT JOIN node__field_cita_invitado ci on nfd.nid = ci.entity_id
LEFT JOIN user__field_departamento d on nfd.uid = d.entity_id
LEFT JOIN user__field_nombre n on nfd.uid = n.entity_id
LEFT JOIN user__field_apellido a on nfd.uid = a.entity_id
INNER JOIN user__roles ur on ur.entity_id = nfd.uid
LEFT JOIN taxonomy_term_field_data term on term.tid = d.field_departamento_target_id
WHERE type = 'cita'";
  if ($worker_uid) {
    $sql .= " AND (uid = $worker_uid OR field_cita_invitado_target_id = $worker_uid)";
  }
  if ($department_tid) {
    $tids = implode(',', $department_tid);
    $sql .= " AND field_departamento_target_id IN ($tids) AND roles_target_id != 'carbray_administrator'";
  }
  $citas = \Drupal::database()->query($sql)->fetchAll();
  return $citas;
}

/**
 * Gets all worker colours stored in {carbray_calendar_colours}
 */
function get_calendar_colours() {
  $colours = \Drupal::database()->query("SELECT uid, colour from carbray_calendar_colours")->fetchAllKeyed();
  return $colours;
}

/**
 * Puts in a table workers and their assigned colour to make the colours legend.
 * @param $colours_array
 *   Array containing worker uid and its assigned colour string.
 *
 * @return array
 *  Table markup.
 */
function get_calendar_colours_legend($colours_array) {
  $header = [
    'Trabajador',
    'Color',
  ];
  $rows = [];
  foreach ($colours_array as $uid => $colour_code) {
    $colour_code = (substr($colour_code, 0, 1) === '#') ? $colour_code : '#' . $colour_code;
    $user = User::load($uid);
    $rows[] = [
      $user->get('field_nombre')->value . ' ' . $user->get('field_apellido')->value,
      Markup::create('<span style="display: inline-block; width: 75px; height: 30px; background-color: ' . $colour_code . '"></span>'),
    ];
  }
  $output = [
    "#type" => 'table',
    "#header" => $header,
    "#rows" => $rows,
  ];
  return $output;
}